### ISSUE TITLE
Problema na responsividade...

### ISSUE THREAD

**Issue by mathmorais** [iuricode/one-page-company#4]
### Em resoluções acima de 2560px, os ícones da div #redes-socials está por cima da div articles

![iuricode github io_one-page-company_ (2)](https://user-images.githubusercontent.com/70591271/102917476-12565c00-4464-11eb-834a-3f03cb8ffb94.png)

Passos para replicar :

- Va até o inicio da pagina
- Abra o dev-tools do seu navegador e, aperte Ctrl+Shift+M para entrar na opção device-tool-bar
- Amplie a resolução até que ela seja maior que 2560px
- Ao ampliar os ícones  vão estar sobrepondo a div articles

**Comment by iuricode** [comment]
Muito obrigado pelo feedback, vou melhorar a responsividade dele em telas maiores!
